INSERT INTO CATEGORY (ID, NAME, PARENT) VALUES (1, 'root', null);

INSERT INTO CATEGORY (ID, NAME, PARENT) VALUES (2, 'Dom', 1);
INSERT INTO CATEGORY (ID, NAME, PARENT) VALUES (3, 'Praca', 1);

INSERT INTO TASK (ID, DATE, DONE, TITLE, CATEGORY_FOREIGN_KEY, CHILD_FOREIGN_KEY, PARENT_FOREIGN_KEY) VALUES (1, null, false, 'Posprzątać garaż', 2, null, null);
INSERT INTO TASK (ID, DATE, DONE, TITLE, CATEGORY_FOREIGN_KEY, CHILD_FOREIGN_KEY, PARENT_FOREIGN_KEY) VALUES (2, null, false, 'Odkurzyć salon', 2, null, null);
INSERT INTO TASK (ID, DATE, DONE, TITLE, CATEGORY_FOREIGN_KEY, CHILD_FOREIGN_KEY, PARENT_FOREIGN_KEY) VALUES (3, null, false, 'Spotkanie z klientem', 3, null, null);
INSERT INTO TASK (ID, DATE, DONE, TITLE, CATEGORY_FOREIGN_KEY, CHILD_FOREIGN_KEY, PARENT_FOREIGN_KEY) VALUES (4, null, true, 'Wydrukować raporty', 3, null, null);
INSERT INTO TASK (ID, DATE, DONE, TITLE, CATEGORY_FOREIGN_KEY, CHILD_FOREIGN_KEY, PARENT_FOREIGN_KEY) VALUES (5, null, true, 'Wysłać faktury', 3, null, null);

UPDATE TASK SET CHILD_FOREIGN_KEY = 2, PARENT_FOREIGN_KEY = null WHERE ID = 1;
UPDATE TASK SET CHILD_FOREIGN_KEY = 3, PARENT_FOREIGN_KEY = 1 WHERE ID = 2;
UPDATE TASK SET CHILD_FOREIGN_KEY = 4, PARENT_FOREIGN_KEY = 2 WHERE ID = 3;
UPDATE TASK SET CHILD_FOREIGN_KEY = 5, PARENT_FOREIGN_KEY = 3 WHERE ID = 4;
UPDATE TASK SET CHILD_FOREIGN_KEY = null, PARENT_FOREIGN_KEY = 4 WHERE ID = 5;
